'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { Building2, Loader2, LogIn, LogOut, Truck } from 'lucide-react';
import { supabase } from '@/lib/supabase';

const REGIONES_CHILE=['Arica y Parinacota','Tarapacá','Antofagasta','Atacama','Coquimbo','Valparaíso','Metropolitana de Santiago','O’Higgins','Maule','Ñuble','Biobío','La Araucanía','Los Ríos','Los Lagos','Aysén','Magallanes y de la Antártica Chilena'];
const inicial={razon_social:'',rut:'',giro:'',contacto_nombre:'',email:'',telefono:'',empresa_direccion:'',empresa_comuna:'',empresa_ciudad:'',empresa_region:'',empresa_pais:'Chile',despacho_a_empresa:true,despacho_direccion:'',despacho_comuna:'',despacho_ciudad:'',despacho_region:'',despacho_pais:'Chile',despacho_referencia:'',volumen_estimado:'',password:'',sitio_web:'',form_started_at:0};
type Producto={id:number;nombre:string;descripcion?:string|null;precio:number;precio_publico:number;imagen?:string|null};
type Mayorista={razon_social:string;estado:'pendiente'|'aprobado'|'rechazado'|'suspendido';pedido_minimo:number;despacho_habilitado:boolean;condicion_pago?:string|null};

export default function MayoristasPage(){
  const [vista,setVista]=useState<'solicitud'|'ingreso'|'cuenta'>('solicitud');
  const [form,setForm]=useState(()=>({...inicial,form_started_at:Date.now()})); const [login,setLogin]=useState({email:'',password:''});
  const [cargando,setCargando]=useState(false); const [mensaje,setMensaje]=useState(''); const [error,setError]=useState('');
  const [mayorista,setMayorista]=useState<Mayorista|null>(null); const [productos,setProductos]=useState<Producto[]>([]);
  async function cargarCuenta(){const sesion=(await supabase.auth.getSession()).data.session;if(!sesion)return;const respuesta=await fetch('/api/mayoristas/catalogo',{headers:{Authorization:`Bearer ${sesion.access_token}`}});const datos=await respuesta.json();if(respuesta.ok){setMayorista(datos.mayorista);setProductos(datos.productos||[]);setVista('cuenta');}}
  useEffect(()=>{void cargarCuenta();},[]);
  async function solicitar(event:React.FormEvent){event.preventDefault();setCargando(true);setError('');const respuesta=await fetch('/api/mayoristas/solicitud',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const datos=await respuesta.json();setCargando(false);if(!respuesta.ok)return setError(datos.error||'No se pudo enviar la solicitud.');setMensaje('Solicitud enviada. Te avisaremos cuando sea aprobada.');setForm({...inicial,form_started_at:Date.now()});setVista('ingreso');}
  async function ingresar(event:React.FormEvent){event.preventDefault();setCargando(true);setError('');const {error}=await supabase.auth.signInWithPassword(login);setCargando(false);if(error)return setError('El correo o la contraseña no coinciden.');await cargarCuenta();}
  async function salir(){await supabase.auth.signOut();setMayorista(null);setProductos([]);setVista('ingreso');}
  const campo=(nombre:keyof typeof inicial,etiqueta:string,tipo='text')=><label className="grid gap-1 text-xs font-black text-[#4B2818]/70">{etiqueta}<input type={tipo} required={!['giro','despacho_referencia','volumen_estimado'].includes(nombre)} value={String(form[nombre])} onChange={(e)=>setForm({...form,[nombre]:e.target.value})} className="h-11 rounded-lg border px-3 text-sm font-bold text-[#2A1710] outline-none focus:border-[#A51F2B]"/></label>;
  const region=(nombre:'empresa_region'|'despacho_region')=><label className="grid gap-1 text-xs font-black text-[#4B2818]/70">Región<select required value={form[nombre]} onChange={(e)=>setForm({...form,[nombre]:e.target.value})} className="h-11 rounded-lg border bg-white px-3 text-sm font-bold text-[#2A1710] outline-none focus:border-[#A51F2B]"><option value="">Seleccionar región</option>{REGIONES_CHILE.map((item)=><option key={item}>{item}</option>)}</select></label>;
  const pais=(nombre:'empresa_pais'|'despacho_pais')=><label className="grid gap-1 text-xs font-black text-[#4B2818]/70">País<select required value={form[nombre]} onChange={(e)=>setForm({...form,[nombre]:e.target.value})} className="h-11 rounded-lg border bg-white px-3 text-sm font-bold text-[#2A1710]"><option value="Chile">Chile</option></select></label>;
  return <main className="min-h-screen bg-[#FFF3DF] px-4 py-8 text-[#2A1710]"><div className="mx-auto max-w-5xl"><Link href="/" className="text-sm font-black text-[#A51F2B]">← Volver a Panadería Maruxa</Link><header className="mt-5 rounded-3xl bg-[#2A1710] p-7 text-white"><div className="flex items-center gap-3"><Truck/><p className="text-xs font-black uppercase tracking-widest text-amber-200">Despacho propio</p></div><h1 className="mt-3 text-4xl font-black">Pastelería Mayorista</h1><p className="mt-2 max-w-2xl text-sm font-bold text-white/70">Precios especiales y despacho para pedidos de mayor volumen. Las cuentas deben ser validadas por Panadería Maruxa.</p></header>
  {vista!=='cuenta'&&<div className="mt-5 flex gap-2"><button onClick={()=>{setVista('solicitud');setError('')}} className={`rounded-full px-5 py-2 text-sm font-black ${vista==='solicitud'?'bg-[#A51F2B] text-white':'bg-white'}`}>Solicitar cuenta</button><button onClick={()=>{setVista('ingreso');setError('')}} className={`rounded-full px-5 py-2 text-sm font-black ${vista==='ingreso'?'bg-[#A51F2B] text-white':'bg-white'}`}>Ingresar</button></div>}
  {mensaje&&<p className="mt-5 rounded-xl bg-emerald-100 p-4 font-bold text-emerald-800">{mensaje}</p>}{error&&<p className="mt-5 rounded-xl bg-red-100 p-4 font-bold text-red-800">{error}</p>}
  {vista==='solicitud'&&<form onSubmit={solicitar} className="mt-5 space-y-6 rounded-3xl bg-white p-6 shadow-sm"><input type="text" name="sitio_web" value={form.sitio_web} onChange={(e)=>setForm({...form,sitio_web:e.target.value})} tabIndex={-1} autoComplete="off" aria-hidden="true" className="absolute left-[-10000px] h-px w-px opacity-0"/><section><h2 className="flex items-center gap-2 text-xl font-black"><Building2/>Datos de la empresa</h2><div className="mt-4 grid gap-4 md:grid-cols-2">{campo('razon_social','Razón social')}{campo('rut','RUT chileno')}{campo('giro','Giro comercial')}{campo('contacto_nombre','Nombre y apellido del contacto')}{campo('email','Correo','email')}{campo('telefono','Teléfono con código de país')}{campo('volumen_estimado','Volumen estimado de compra')}{campo('password','Contraseña','password')}</div><p className="mt-3 text-xs font-bold text-[#4B2818]/60">Validaremos el dígito verificador del RUT. La contraseña debe tener 10 caracteres, mayúscula, minúscula y número.</p></section><section><div className="flex flex-wrap items-end justify-between gap-2"><h2 className="text-xl font-black">Dirección de la empresa</h2><span className="text-xs font-bold text-[#4B2818]/55">Despachos disponibles actualmente en Chile</span></div><div className="mt-4 grid gap-4 md:grid-cols-2">{pais('empresa_pais')}{region('empresa_region')}{campo('empresa_comuna','Comuna')}{campo('empresa_ciudad','Ciudad o localidad')}{campo('empresa_direccion','Calle y número')}</div></section><section><label className="flex items-center gap-3 rounded-xl border bg-[#FFF9EF] p-4 font-black"><input type="checkbox" checked={form.despacho_a_empresa} onChange={(e)=>setForm({...form,despacho_a_empresa:e.target.checked})} className="h-5 w-5 accent-[#A51F2B]"/>Usar la dirección de la empresa para el despacho</label>{!form.despacho_a_empresa&&<><h2 className="mt-5 text-xl font-black">Dirección de despacho</h2><div className="mt-4 grid gap-4 md:grid-cols-2">{pais('despacho_pais')}{region('despacho_region')}{campo('despacho_comuna','Comuna')}{campo('despacho_ciudad','Ciudad o localidad')}{campo('despacho_direccion','Calle y número')}{campo('despacho_referencia','Referencia')}</div></>}</section><button disabled={cargando} className="inline-flex h-12 items-center gap-2 rounded-xl bg-[#A51F2B] px-7 font-black text-white disabled:opacity-50">{cargando&&<Loader2 className="h-4 w-4 animate-spin"/>}Enviar solicitud</button></form>}
  {vista==='ingreso'&&<form onSubmit={ingresar} className="mx-auto mt-8 max-w-md rounded-3xl bg-white p-7 shadow-sm"><LogIn className="h-8 w-8 text-[#A51F2B]"/><h2 className="mt-3 text-2xl font-black">Ingresar a mi cuenta</h2><div className="mt-5 grid gap-4"><label className="grid gap-1 text-xs font-black">Correo<input type="email" required value={login.email} onChange={(e)=>setLogin({...login,email:e.target.value})} className="h-11 rounded-lg border px-3"/></label><label className="grid gap-1 text-xs font-black">Contraseña<input type="password" required value={login.password} onChange={(e)=>setLogin({...login,password:e.target.value})} className="h-11 rounded-lg border px-3"/></label></div><button disabled={cargando} className="mt-5 h-11 w-full rounded-lg bg-[#A51F2B] font-black text-white">Ingresar</button></form>}
  {vista==='cuenta'&&mayorista&&<section className="mt-6"><div className="flex flex-wrap items-center justify-between gap-3 rounded-2xl bg-white p-5"><div><p className="text-xs font-black uppercase text-[#A51F2B]">{mayorista.razon_social}</p><h2 className="text-2xl font-black">Estado: {mayorista.estado}</h2></div><button onClick={salir} className="inline-flex items-center gap-2 rounded-lg border px-4 py-2 font-black"><LogOut className="h-4 w-4"/>Salir</button></div>{mayorista.estado!=='aprobado'?<div className="mt-5 rounded-2xl border border-amber-300 bg-amber-50 p-6"><h3 className="text-xl font-black">Tu solicitud está {mayorista.estado}</h3><p className="mt-2 font-bold text-[#4B2818]/70">Los precios mayoristas se habilitarán después de la revisión administrativa.</p></div>:<><div className="mt-5 grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-white p-4"><p className="text-xs font-black uppercase">Pedido mínimo</p><p className="text-xl font-black">${Number(mayorista.pedido_minimo||0).toLocaleString('es-CL')}</p></div><div className="rounded-xl bg-white p-4"><p className="text-xs font-black uppercase">Despacho</p><p className="text-xl font-black">{mayorista.despacho_habilitado?'Habilitado':'Por confirmar'}</p></div><div className="rounded-xl bg-white p-4"><p className="text-xs font-black uppercase">Condición de pago</p><p className="text-xl font-black">{mayorista.condicion_pago||'Por definir'}</p></div></div><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{productos.map((p)=><article key={p.id} className="rounded-2xl bg-white p-5 shadow-sm"><h3 className="font-black">{p.nombre}</h3><p className="mt-1 text-sm text-[#4B2818]/60">{p.descripcion}</p><p className="mt-4 text-2xl font-black text-[#A51F2B]">${p.precio.toLocaleString('es-CL')}</p></article>)}</div></>}</section>}
  </div></main>;
}
