create table if not exists public.eventos_seguridad (
  id bigint generated by default as identity primary key,
  empresa_id uuid references public.empresas(id) on delete cascade,
  created_at timestamptz not null default now(),
  tipo text not null,
  ruta text not null,
  motivo text not null,
  ip_hash text,
  user_agent text,
  referer text,
  detalles jsonb not null default '{}'::jsonb
);

create index if not exists eventos_seguridad_empresa_fecha_idx
  on public.eventos_seguridad (empresa_id, created_at desc);
create index if not exists eventos_seguridad_tipo_fecha_idx
  on public.eventos_seguridad (tipo, created_at desc);

alter table public.eventos_seguridad enable row level security;

drop policy if exists "eventos_seguridad_erp_lectura" on public.eventos_seguridad;
create policy "eventos_seguridad_erp_lectura"
  on public.eventos_seguridad for select to authenticated
  using (empresa_id = public.usuario_empresa_id());

